[2025-05-13T18:29:27.724Z] Iniciando proceso de sincronización (ID: 1)
[2025-05-13T18:29:28.889Z] ERROR: Error desconocido
[2025-05-13T18:29:28.891Z] Stack: No disponible
[2025-05-13T18:44:42.006Z] Iniciando proceso de sincronización (ID: 2)
[2025-05-13T18:44:42.029Z] ERROR: 
Invalid `prisma.syncMetadata.findUnique()` invocation in
D:\Personales\Next\student_tracking\src\lib\sync.ts:519:46

  516 async function obtenerUltimaActualizacion(
  517   tabla: string
  518 ): Promise<string | null> {
→ 519   const metadata = await prisma.syncMetadata.findUnique(
Error validating datasource `db`: the URL must start with the protocol `prisma://`
[2025-05-13T18:44:42.030Z] Stack: PrismaClientKnownRequestError: 
Invalid `prisma.syncMetadata.findUnique()` invocation in
D:\Personales\Next\student_tracking\src\lib\sync.ts:519:46

  516 async function obtenerUltimaActualizacion(
  517   tabla: string
  518 ): Promise<string | null> {
→ 519   const metadata = await prisma.syncMetadata.findUnique(
Error validating datasource `db`: the URL must start with the protocol `prisma://`
    at zn.handleRequestError (D:\Personales\Next\student_tracking\node_modules\@prisma\client\runtime\library.js:121:7459)
    at zn.handleAndLogRequestError (D:\Personales\Next\student_tracking\node_modules\@prisma\client\runtime\library.js:121:6784)
    at zn.request (D:\Personales\Next\student_tracking\node_modules\@prisma\client\runtime\library.js:121:6491)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async l (D:\Personales\Next\student_tracking\node_modules\@prisma\client\runtime\library.js:130:9778)
    at async obtenerUltimaActualizacion (D:\Personales\Next\student_tracking\src\lib\sync.ts:519:20)
    at async sincronizarEstudiantes (D:\Personales\Next\student_tracking\src\lib\sync.ts:47:31)
    at async sincronizarDesdeSupabase (D:\Personales\Next\student_tracking\src\lib\sync.ts:13:5)
    at async main (D:\Personales\Next\student_tracking\scripts\sync.ts:60:5)
